

const LOGINREQ='LOGINREQ';
const LOGINSUCCES='LOGINSUCCESS';
const LOGINERROR='LOGINERROR';

const LOGOUT='LOGOUT'


const REGISTERREQ='REGISTERREQ';
const REGISTERSUCCESS='REGISTERSUCCESS';
const REGISTERERROR='REGISTERERROR'


export {LOGINERROR,LOGINREQ,LOGINSUCCES,REGISTERERROR,REGISTERSUCCESS,REGISTERREQ,LOGOUT}