

const GETREQ='GETREQ';
const GETDATAREQSUCCESS='GETDATAREQSUCCESS';
const GETDATAREQERROR='GETDATAREQERROR';

const SUBMITREQ='SUBMITREQ';
const SUBMITSUCCESS='SUBMITSUCCESS';
const SUBMITERROR='SUBMITERROR';


const EDITREQ='EDITREQ';
 const EDITREQSUCC='EDITREQSUCC'
 const EDITREQFAIL='EDITREQFAIL'

 const TOGGLE='TOGGLE'
 const TOGGLEREQ='TOGGLEREQ';
  

 const DELETEreq="DELETEreq"
 const DELSUC='DELSUC'


export { TOGGLEREQ, DELETEreq,DELSUC, TOGGLE, GETREQ,GETDATAREQSUCCESS,GETDATAREQERROR,SUBMITREQ,SUBMITSUCCESS,SUBMITERROR ,EDITREQ,EDITREQSUCC,EDITREQFAIL}