

const GETREQ='GETREQ';
const GETDATAREQSUCCESS='GETDATAREQSUCCESS';
const GETDATAREQERROR='GETDATAREQERROR';

const SUBMITREQ='SUBMITREQ';
const SUBMITSUCCESS='SUBMITSUCCESS';
const SUBMITERROR='SUBMITERROR';


export {GETREQ,GETDATAREQSUCCESS,GETDATAREQERROR,SUBMITREQ,SUBMITSUCCESS,SUBMITERROR}